### ISSUE TITLE
Is it possible to do Blur within this effect?

### ISSUE THREAD

**Issue by krisives** [zzag/kwin-effects-yaml#4]
One of the things I noticed with the original magic lamp effect was that [Blur is not applied to the effect](https://bugs.kde.org/show_bug.cgi?id=398648). Looking at the bug report, it's actually *you* that educated me that it's not possible with the current setup of the Blur plugin.

But, is it possible to add the Blur effect itself into this magic lamp or a forked version of this? I ask because I know it's already doing some render-to-texture. I understand it may be seen as a hack and I'm simply asking for information about how feasible it is and I'm willing to try to do the hacking if you can give me a little guidance.

Thanks again for all your work you do on KDE.

**Comment by zzag** [comment]
No, it's not.

(a) I'd need to copy some code from the blur effect;
(b) This effect would need to perform quadrilateral interpolation, which is a whole different chapter;
(c) Doing blur in this effect doesn't make sense.
